services:
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - api_key=${api_key}
      - fmcsa_api_key=${fmcsa_api_key}
      - allowed_origins=${allowed_origins}
      - DATABASE_URL=postgresql://postgres:password@db:5432/loadsdb3
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=loadsdb3
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql    # Add this line
    ports:
      - "5432:5432"

volumes:
  postgres_data: